---
- name: Capture Swarm Cluster Worker Token
  become: yes
  become_user: ubuntu
  shell: ssh ubuntu@172.42.42.1 sudo docker swarm join-token -q worker 2>/dev/null
  register: worker_token
  changed_when: false

- name: Debug
  debug:
    msg: "TOKEN: {{ worker_token.stdout }}"

- name: Join Swarm Cluster
  become: yes
  command: "docker swarm join --token {{ worker_token.stdout }} 172.42.42.1:2377"
