---
- name: Ensure SSH Directories
  become: yes
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Copy SSH Key Files
  become: yes
  copy:
    src: files/{{ item }}
    dest: /home/ubuntu/.ssh/{{ item }}
    owner: ubuntu
    group: ubuntu
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub
    - config

- name: Ensure Authorized SSH Key
  become: yes
  authorized_key:
    user: ubuntu
    key:  "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
    state: present

- name: Update Apt Cache
  become: yes
  apt:
    update_cache: yes

- name: Ensure Transport and Certificates
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "curl"
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common" 

- name: Ensure Docker Keys
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  tags:
    - swarm

- name: Ensure Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags:
    - swarm

- name: Ensure older docker artifacts are not present
  become: yes
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: absent
  with_items:
    - "docker"
    - "docker-engine"
    - "docker.io"
    - "lxc-docker"

- name: Ensure Docker
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - "linux-image-extra-4.4.0-93-generic"
    - "linux-image-extra-virtual"
    - "software-properties-common"
    - "docker-ce"

- name: Ensure Ubuntu User in Docker Group
  user:
    name: ubuntu
    append: yes
    groups: docker
