---
- name: Ensure SSH Directories
  become: yes
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Copy SSH Key Files
  become: yes
  copy:
    src: files/{{ item }}
    dest: /home/ubuntu/.ssh/{{ item }}
    owner: ubuntu
    group: ubuntu
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub
    - config

- name: Ensure Authorized SSH Key
  become: yes
  authorized_key:
    user: ubuntu
    key:  "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
    state: present

- name: Update Apt Cache
  become: yes
  apt:
    update_cache: yes

- name: Ensure Transport and Certificates
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "apt-transport-https"
    - "ca-certificates"

- name: Ensure Docker Keys
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  tags:
    - swarm

- name: Ensure Docker Repository
  become: yes
  lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/docker.list
    line: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    owner: root
    group: root
    mode: 0644
  tags:
    - swarm

- name: Update Apt Cache with Docker
  become: yes
  apt:
    update_cache: yes
    name: lxc-docker
    state: absent

- name: Update Apt Cache Policy
  become: yes
  command: apt-cache policy docker-engine

- name: Ensure Docker
  apt:
    update_cache: yes
    name: docker-engine
    state: latest

- name: Ensure Ubuntu User in Docker Group
  user:
    name: ubuntu
    append: yes
    groups: docker
